### ISSUE TITLE
Configuration methods

### ISSUE THREAD

**Issue by beyond9thousand** [bryanbecker/glitchdm#4]
Not really an issue but can you give me little guidance on how I could change the animated background? I love the theme nevertheless

And perhaps if there was a way to change the font sizes for all the elements displayed on screen

Speficially the font sizes for each of these
![image](https://user-images.githubusercontent.com/77363063/172119867-4df4973f-aab4-4c7d-94e4-bcc3452faa17.png)

**Comment by bryanbecker** [comment]
Oh man, it's been a while, but it's basically a website.

You should find what you need to edit in [index.html](https://github.com/bryanbecker/glitchdm/blob/master/index.html) & the corresponding css file in https://github.com/bryanbecker/glitchdm/blob/master/css/bootstrap/theme.css

**Comment by beyond9thousand** [comment]
> Oh man, it's been a while, but it's basically a website.
> 
> You should find what you need to edit in [index.html](https://github.com/bryanbecker/glitchdm/blob/master/index.html) & the corresponding css file in https://github.com/bryanbecker/glitchdm/blob/master/css/bootstrap/theme.css

Thank you so much for your reply!

P.S. I love the work you've done on this. I appreciate it

**Comment by beyond9thousand** [comment]
What would I need to do if I wanted to replace the background animation entirely? I noticed that you implemented some sophisticated methods (for me) to implement the glitch lines that keep rolling. If I had a loop-able gif image, could I perhaps use that instead?

**Comment by bryanbecker** [comment]
I couldn't figure out how to use a gif -- maybe it's easier now with new libraries out?
